In [1]:
import numpy as np
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
A=np.arange(24).reshape((3,4,2))

In [5]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
print(A)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [7]:
print(A.flatten(order='C'))
print(A.flatten(order='F'))
print(A.ravel(order='C'))
print(A.ravel(order='F'))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]


In [20]:
B=np.arange(12).reshape((3,2,2))
C=np.arange(100,112).reshape((3,2,2))
D=np.concatenate((B,C),axis=2)
D

array([[[  0,   1, 100, 101],
        [  2,   3, 102, 103]],

       [[  4,   5, 104, 105],
        [  6,   7, 106, 107]],

       [[  8,   9, 108, 109],
        [ 10,  11, 110, 111]]])

In [15]:
print(np.vstack((B,C)))
print('=============')
print(np.hstack((B,C)))
print('=============')
print(np.dstack((B,C)))

[[[  0   1]
  [  2   3]]

 [[  4   5]
  [  6   7]]

 [[  8   9]
  [ 10  11]]

 [[100 101]
  [102 103]]

 [[104 105]
  [106 107]]

 [[108 109]
  [110 111]]]
[[[  0   1]
  [  2   3]
  [100 101]
  [102 103]]

 [[  4   5]
  [  6   7]
  [104 105]
  [106 107]]

 [[  8   9]
  [ 10  11]
  [108 109]
  [110 111]]]
[[[  0   1 100 101]
  [  2   3 102 103]]

 [[  4   5 104 105]
  [  6   7 106 107]]

 [[  8   9 108 109]
  [ 10  11 110 111]]]


In [21]:
D[:,np.newaxis]

array([[[[  0,   1, 100, 101],
         [  2,   3, 102, 103]]],


       [[[  4,   5, 104, 105],
         [  6,   7, 106, 107]]],


       [[[  8,   9, 108, 109],
         [ 10,  11, 110, 111]]]])

In [23]:
x=np.array([[1,2],[3,4]])
np.tile(x,(3,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [25]:
np.row_stack((B,C))

array([[[  0,   1],
        [  2,   3]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]],

       [[100, 101],
        [102, 103]],

       [[104, 105],
        [106, 107]],

       [[108, 109],
        [110, 111]]])